/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

/**
 *
 * @author clientein
 */

import javax.swing.*;
import java.awt.*;
import controle.Frm_LoginFunc;
import java.sql.Statement;
import conexao.Conexao;  
import controle.Frm_MenuCliente;
import java.awt.font.TextAttribute;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Map;
import java.sql.ResultSet;
import javax.swing.text.MaskFormatter;



import javax.swing.text.MaskFormatter;

public class Frm_SignUp extends javax.swing.JFrame {
 
    Conexao con_cliente;
    /**
     * Creates new form Frm_LoginFunc
     */
    public Frm_SignUp() {
        super("Cadastro de clientes");
        con_cliente = new Conexao();
        con_cliente.conecta();

        
        initComponents();
        ImageIcon icone = new ImageIcon("src/img/NOVA.png");
        setIconImage(icone.getImage());
        txtSenha.setEchoChar('•');
        txtcSenha.setEchoChar('•');
       
        con_cliente.executaSQL("select * from cliente order by CodCliente");
         Font font = lLogin.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lLogin.setFont(font.deriveFont(attributes));
        

    }

  

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        rLogin1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lSenha2 = new javax.swing.JLabel();
        txtcSenha = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtSenha = new javax.swing.JPasswordField();
        lSenha1 = new javax.swing.JLabel();
       
        lEmail1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lSenha3 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jInternalFrame1.setVisible(true);
              try {
            MaskFormatter dataFormatter = new MaskFormatter("####-##-##");
            dataFormatter.setPlaceholderCharacter('_');
            txtDataNasc = new JFormattedTextField(dataFormatter);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 14, 125));
        setName("login"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(24, 26, 33));

        btnEnviar.setBackground(new java.awt.Color(75, 65, 119));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setToolTipText("");
        btnEnviar.setBorder(null);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(75, 65, 119));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(75, 65, 119));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nova_resized.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(627, 398));
        jLabel5.setMinimumSize(new java.awt.Dimension(627, 398));
        jLabel5.setPreferredSize(new java.awt.Dimension(627, 398));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNome.setBackground(new java.awt.Color(51, 54, 61));
        txtNome.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setBorder(null);
        txtNome.setName("txtNome"); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lEmail.setForeground(new java.awt.Color(153, 152, 255));
        lEmail.setText("Nome completo:");
        lEmail.setName("E-mail: "); // NOI18N

        lSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSenha.setForeground(new java.awt.Color(153, 152, 255));
        lSenha.setText("Nickname(apelido):");
        lSenha.setName("E-mail: "); // NOI18N

        lLogin.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lLogin.setForeground(new java.awt.Color(153, 152, 255));
        lLogin.setText("Já possuo cadastro");
        lLogin.setName("E-mail: "); // NOI18N
        lLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loguinho(evt);
            }
        });

        rLogin1.setBackground(new java.awt.Color(24, 26, 33));
        rLogin1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        rLogin1.setForeground(new java.awt.Color(255, 255, 255));
        rLogin1.setText("Sign Up");
        rLogin1.setBorder(null);
        rLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLogin1ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(51, 54, 61));
        jSeparator2.setForeground(new java.awt.Color(51, 54, 61));

        lSenha2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSenha2.setForeground(new java.awt.Color(153, 152, 255));
        lSenha2.setText("Data de Nascimento:");
        lSenha2.setName("E-mail: "); // NOI18N

        txtcSenha.setBackground(new java.awt.Color(51, 54, 61));
        txtcSenha.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtcSenha.setForeground(new java.awt.Color(225, 225, 225));
        txtcSenha.setToolTipText("");
        txtcSenha.setBorder(null);
        txtcSenha.setName("txtSenha"); // NOI18N
        txtcSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcSenhaActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 54, 61));
        jSeparator3.setForeground(new java.awt.Color(51, 54, 61));

        jSeparator4.setBackground(new java.awt.Color(51, 54, 61));
        jSeparator4.setForeground(new java.awt.Color(51, 54, 61));

        txtSenha.setBackground(new java.awt.Color(51, 54, 61));
        txtSenha.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(225, 225, 225));
        txtSenha.setToolTipText("");
        txtSenha.setBorder(null);
        txtSenha.setName("txtSenha"); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        lSenha1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSenha1.setForeground(new java.awt.Color(153, 152, 255));
        lSenha1.setText("Confirmar senha:");
        lSenha1.setName("E-mail: "); // NOI18N

        txtDataNasc.setBackground(new java.awt.Color(51, 54, 61));
        txtDataNasc.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtDataNasc.setForeground(new java.awt.Color(204, 204, 204));
        txtDataNasc.setBorder(null);
        txtDataNasc.setName("txtEmail"); // NOI18N
        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });

        lEmail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lEmail1.setForeground(new java.awt.Color(153, 152, 255));
        lEmail1.setText("Senha:");
        lEmail1.setName("E-mail: "); // NOI18N

        txtEmail.setBackground(new java.awt.Color(51, 54, 61));
        txtEmail.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setBorder(null);
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lSenha3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSenha3.setForeground(new java.awt.Color(153, 152, 255));
        lSenha3.setText("E-mail:");
        lSenha3.setName("E-mail: "); // NOI18N

        txtNickname.setBackground(new java.awt.Color(51, 54, 61));
        txtNickname.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtNickname.setForeground(new java.awt.Color(204, 204, 204));
        txtNickname.setBorder(null);
        txtNickname.setName("txtNome"); // NOI18N
        txtNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicknameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail)
                    .addComponent(lSenha)
                    .addComponent(lSenha2)
                    .addComponent(lEmail)
                    .addComponent(lSenha1)
                    .addComponent(lEmail1)
                    .addComponent(txtSenha)
                    .addComponent(txtcSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lSenha3)
                    .addComponent(txtNickname)
                    .addComponent(txtNome)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(rLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(rLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSenha2)
                .addGap(4, 4, 4)
                .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lSenha3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lLogin))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLogin1ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        txtNickname.setText("");
        txtDataNasc.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtcSenha.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
                                       

    String Nome = txtNome.getText();
    String Nickname = txtNickname.getText();
    String DataNasc = txtDataNasc.getText();
    String Email = txtEmail.getText();
    String senha = new String(txtSenha.getPassword());
    String ConfirmarSenha = new String(txtcSenha.getPassword());

    if (Email.isEmpty() || senha.isEmpty() || ConfirmarSenha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!isSenhaValida(senha)) {
        JOptionPane.showMessageDialog(this, "A senha deve ter pelo menos 12 caracteres, incluindo números e pontuação!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {

        String checkClienteQuery = "SELECT 1 FROM Cliente WHERE Nickname = ? OR Email = ?";
        PreparedStatement pstmtCliente = con_cliente.prepareStatement(checkClienteQuery);
        pstmtCliente.setString(1, Nickname);
        pstmtCliente.setString(2, Email);
        
        ResultSet rsCliente = pstmtCliente.executeQuery();
        
        if (rsCliente.next()) {
            JOptionPane.showMessageDialog(null, "Já existe um usuário com esse Nickname ou Email!", "Erro", JOptionPane.ERROR_MESSAGE);
            return; 
        }


        if (senha.equals(ConfirmarSenha)) {
            String insert_sql = "insert into Cliente (Nome, Nickname, DataNasc, CPF, Senha, Email) values (?, ?, ?, '', ?, ?)";
            PreparedStatement pstmtInsert = con_cliente.prepareStatement(insert_sql);
            pstmtInsert.setString(1, Nome);
            pstmtInsert.setString(2, Nickname);
            pstmtInsert.setString(3, DataNasc);
            pstmtInsert.setString(4, senha);
            pstmtInsert.setString(5, Email);

            pstmtInsert.executeUpdate();

            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

            Frm_MenuCliente menuCliente = new Frm_MenuCliente();
            menuCliente.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Senhas incoerentes!", "mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            txtSenha.setText("");
            txtcSenha.setText("");
        }
    } catch (SQLException errosql) {
        JOptionPane.showMessageDialog(null, "Não foi possível se cadastrar! : \n" + errosql, "mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
}

// Método para validar a senha
private boolean isSenhaValida(String senha) {
    String regex = "^(?=.*[0-9])(?=.*[\\p{Punct}]).{12,}$";
    return senha.matches(regex);

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void loguinho(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguinho
  
            Frm_Login menu = new Frm_Login();
            menu.setVisible(true);
            dispose(); 

    }//GEN-LAST:event_loguinho

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtcSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcSenhaActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            Conexao con_cliente;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
  

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmail1;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lSenha1;
    private javax.swing.JLabel lSenha2;
    private javax.swing.JLabel lSenha3;
    private javax.swing.JTextField rLogin1;
	private JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtcSenha;
    // End of variables declaration//GEN-END:variables
}



