      /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package controle;
import conexao.Conexao; 
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author henri
 */
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
             
public class Jogo extends JDialog {
  Conexao con_loja_de_jogos;

    /**
     * Creates new form Jogo
     * @param owner
     * @param title
     * @param modal
     */
    public Jogo(Frame owner, String title, boolean modal) {
        super(owner, title, modal);
        initComponents();
        ImageIcon icone = new ImageIcon("src/img/NOVA.png");
        setIconImage(icone.getImage());
        con_loja_de_jogos = new Conexao();
        con_loja_de_jogos.conecta();
    
             addWindowListener(new WindowAdapter() {
            @Override
                public void windowOpened(WindowEvent e) {
                consultarFaixaEtaria();
                consultarOBS();
            }
        });

        
    txtCodFaixaEtaria.addKeyListener(new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
        consultarFaixaEtaria();
 
    }
});
txtReqMinId.addKeyListener(new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
        consultarOBS();
    }
});

        con_loja_de_jogos.executaSQL("select * from jogo order by CodJogo");
        preencherTabela();
        posicionarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbljogo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnLogin2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtCodFaixaEtaria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAvaliacao = new javax.swing.JTextField();
        txtDtLancamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtCodJogo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtReqMinId = new javax.swing.JTextField();
        rReqMinId = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnGravar = new javax.swing.JButton();
        txtPreco = new javax.swing.JTextField();
        rReqMinId1 = new javax.swing.JLabel();
        txtFaixaEtaria = new javax.swing.JTextField();
        txtOBS = new javax.swing.JTextField();
        rReqMinId2 = new javax.swing.JLabel();
        rReqMinId3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnPrimeiro = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        rPesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(24, 26, 33));
        jPanel2.setPreferredSize(new java.awt.Dimension(851, 1107));

        tbljogo.setBackground(new java.awt.Color(51, 54, 61));
        tbljogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbljogo.setForeground(new java.awt.Color(204, 204, 204));
        tbljogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CodJogo", "Nome", "DtLancamento", "Avaliacao", "CodFaixaEtaria", "ReqMinId", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbljogo.setName("tbljogo"); // NOI18N
        jScrollPane2.setViewportView(tbljogo);

        jPanel3.setBackground(new java.awt.Color(75, 65, 119));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nova_resized.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(627, 398));
        jLabel9.setMinimumSize(new java.awt.Dimension(627, 398));
        jLabel9.setPreferredSize(new java.awt.Dimension(627, 398));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnLogin2.setBackground(new java.awt.Color(75, 65, 119));
        btnLogin2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnLogin2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin2.setText("NOVA Indie");
        btnLogin2.setName("btnLogin"); // NOI18N
        btnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(51, 54, 61));

        txtCodFaixaEtaria.setBackground(new java.awt.Color(75, 77, 77));
        txtCodFaixaEtaria.setForeground(new java.awt.Color(225, 225, 225));
        txtCodFaixaEtaria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodFaixaEtaria.setName("txtCodFaixaEtaria"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código de Faixa Etária");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Avaliações");

        txtAvaliacao.setBackground(new java.awt.Color(75, 77, 77));
        txtAvaliacao.setForeground(new java.awt.Color(225, 225, 225));
        txtAvaliacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAvaliacao.setName("txtAvaliacao"); // NOI18N
        txtAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvaliacaoActionPerformed(evt);
            }
        });

        txtDtLancamento.setBackground(new java.awt.Color(75, 77, 77));
        txtDtLancamento.setForeground(new java.awt.Color(225, 225, 225));
        txtDtLancamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDtLancamento.setName("txtDtLancamento"); // NOI18N
        txtDtLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtLancamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data de Lançamento");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");

        txtnome.setBackground(new java.awt.Color(75, 77, 77));
        txtnome.setForeground(new java.awt.Color(225, 225, 225));
        txtnome.setToolTipText("");
        txtnome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnome.setInheritsPopupMenu(true);
        txtnome.setName("txtnome"); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        txtCodJogo.setBackground(new java.awt.Color(75, 77, 77));
        txtCodJogo.setForeground(new java.awt.Color(225, 225, 225));
        txtCodJogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodJogo.setName("txtCodJogo"); // NOI18N
        txtCodJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodJogoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código do Jogo");

        jLabel7.setBackground(new java.awt.Color(75, 65, 119));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CAMPO JOGO");

        txtReqMinId.setBackground(new java.awt.Color(75, 77, 77));
        txtReqMinId.setForeground(new java.awt.Color(225, 225, 225));
        txtReqMinId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtReqMinId.setName("txtReqMinId"); // NOI18N

        rReqMinId.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rReqMinId.setForeground(new java.awt.Color(255, 255, 255));
        rReqMinId.setText("Código de Requisitos Mínimos");
        rReqMinId.setName("rReqMinId"); // NOI18N

        btnExcluir.setBackground(new java.awt.Color(75, 65, 119));
        btnExcluir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(75, 65, 119));
        btnAlterar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(75, 65, 119));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setName("btnLimpar"); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(75, 65, 119));
        btnNovo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo Registro");
        btnNovo.setName("btnnovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setBackground(new java.awt.Color(75, 65, 119));
        btnGravar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("Gravar");
        btnGravar.setName("btnLimpar"); // NOI18N
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        txtPreco.setBackground(new java.awt.Color(75, 77, 77));
        txtPreco.setForeground(new java.awt.Color(225, 225, 225));
        txtPreco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPreco.setName("txtReqMinId"); // NOI18N

        rReqMinId1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rReqMinId1.setForeground(new java.awt.Color(255, 255, 255));
        rReqMinId1.setText("Preço do Jogo");
        rReqMinId1.setName("rReqMinId"); // NOI18N

        txtFaixaEtaria.setEditable(false);
        txtFaixaEtaria.setBackground(new java.awt.Color(57, 57, 58));
        txtFaixaEtaria.setForeground(new java.awt.Color(225, 225, 225));
        txtFaixaEtaria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFaixaEtaria.setName("txtGenero"); // NOI18N

        txtOBS.setEditable(false);
        txtOBS.setBackground(new java.awt.Color(57, 57, 58));
        txtOBS.setForeground(new java.awt.Color(225, 225, 225));
        txtOBS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtOBS.setName("txtGenero"); // NOI18N

        rReqMinId2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rReqMinId2.setForeground(new java.awt.Color(255, 255, 255));
        rReqMinId2.setText("Classificação Indicativa");
        rReqMinId2.setName("rReqMinId"); // NOI18N

        rReqMinId3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rReqMinId3.setForeground(new java.awt.Color(255, 255, 255));
        rReqMinId3.setText("Observações da máquina");
        rReqMinId3.setName("rReqMinId"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(rReqMinId)
                            .addComponent(rReqMinId1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodJogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtLancamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(txtAvaliacao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtReqMinId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodFaixaEtaria, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rReqMinId2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rReqMinId3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOBS, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCodFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReqMinId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rReqMinId)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rReqMinId1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rReqMinId2)
                            .addComponent(txtFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rReqMinId3))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnNovo.getAccessibleContext().setAccessibleDescription("");

        jLabel8.setBackground(new java.awt.Color(75, 65, 119));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tabela de Jogos");

        btnAnterior.setBackground(new java.awt.Color(75, 65, 119));
        btnAnterior.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Anterior");
        btnAnterior.setName("btnAnterior"); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setBackground(new java.awt.Color(75, 65, 119));
        btnUltimo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnUltimo.setForeground(new java.awt.Color(255, 255, 255));
        btnUltimo.setText("Último");
        btnUltimo.setActionCommand("Ùltimo");
        btnUltimo.setName("btnUltimo"); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnProximo.setBackground(new java.awt.Color(75, 65, 119));
        btnProximo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnProximo.setForeground(new java.awt.Color(255, 255, 255));
        btnProximo.setText("Próximo");
        btnProximo.setName("btnProximo"); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));

        btnPrimeiro.setBackground(new java.awt.Color(75, 65, 119));
        btnPrimeiro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnPrimeiro.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.setActionCommand("Ùltimo");
        btnPrimeiro.setName("btnUltimo"); // NOI18N
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(75, 65, 119));
        btnPesquisar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setLabel("Pesquisar");
        btnPesquisar.setName("btnLimpar"); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.setBackground(new java.awt.Color(75, 77, 77));
        txtPesquisar.setForeground(new java.awt.Color(225, 225, 225));
        txtPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPesquisar.setName("txtEmail"); // NOI18N

        rPesquisar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        rPesquisar.setText("Pesquisar por Código:");
        rPesquisar.setName("rPesquisar"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(387, 387, 387)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(rPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnPesquisar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
                try {
                    con_loja_de_jogos.resultset.previous();
                    mostrar_Dados();
                    consultarFaixaEtaria();
                    consultarOBS();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
                try {
                    con_loja_de_jogos.resultset.next();
                    mostrar_Dados();
                    consultarFaixaEtaria();
                    consultarOBS();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }           
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
     try {
                    con_loja_de_jogos.resultset.last();
                    mostrar_Dados();
                    consultarFaixaEtaria();
                    consultarOBS();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        txtCodJogo.setText("");
        txtnome.setText("");
        txtDtLancamento.setText("");
        txtAvaliacao.setText("");
        txtCodFaixaEtaria.setText("");
        txtReqMinId.setText("");
        txtPreco.setText("");
        txtCodJogo.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
                String nome = txtnome.getText();
                String dtLancamento = txtDtLancamento.getText();
                String avaliacao = txtAvaliacao.getText();
                String CodFaixaEtaria = txtCodFaixaEtaria.getText();
                String ReqMinId = txtReqMinId.getText();
                String Preco = txtPreco.getText();
                String sql;
                String msg = "";

                try {
                    
             
                        String checkFaixaEtariaQuery = "SELECT 1 FROM ClassificacaoIndicativa WHERE CodFaixaEtaria = ?";
                        PreparedStatement pstmtFaixaEtaria = con_loja_de_jogos.prepareStatement(checkFaixaEtariaQuery);
                        pstmtFaixaEtaria.setString(1, CodFaixaEtaria);
                        ResultSet rsClassificacaoIndicativa = pstmtFaixaEtaria.executeQuery();

    if (!rsClassificacaoIndicativa.next()) {
        JOptionPane.showMessageDialog(null, "Classificação não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  
    }
    
                        String checkOBSQuery = "SELECT 6 FROM ReqMinimos WHERE ReqMinId = ?";
                        PreparedStatement pstmtOBS = con_loja_de_jogos.prepareStatement(checkOBSQuery);
                        pstmtOBS.setString(1, ReqMinId);
                        ResultSet rsOBS = pstmtOBS.executeQuery();

    if (!rsOBS.next()) {
        JOptionPane.showMessageDialog(null, "Observações não encontradas!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  
    }

                    if (txtCodJogo.getText().equals("")) {
                        sql = "insert into jogo (nome, dtLancamento, avaliacao, CodFaixaEtaria, ReqMinId, Preco) values ('" + nome + "','" + dtLancamento + "','" + avaliacao + "','" + CodFaixaEtaria + "','" + ReqMinId  + "','" + Preco  + "')";
                        msg = "Gravação de um novo registro";
                    } else {
                        sql = "update jogo set nome='" + nome + "', DtLancamento='" +dtLancamento + "', avaliacao='" + avaliacao + "', CodFaixaEtaria='" + CodFaixaEtaria + "', ReqMinId='" + ReqMinId + "', Preco='" + Preco + "' where CodJogo=" + txtCodJogo.getText();
                        msg = "Alteração de registro";
                    }
                    con_loja_de_jogos.statement.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, msg + " realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

                    con_loja_de_jogos.executaSQL("select * from jogo order by CodJogo");
                    preencherTabela();

                } catch (SQLException errosql) {
                    JOptionPane.showMessageDialog(null, "\n Erro na gravação \n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
                String sql = "";

                try {
                    int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
                    if (resposta == 0) {
                        sql = "delete from jogo where CodJogo =" + txtCodJogo.getText();
                        int excluir = con_loja_de_jogos.statement.executeUpdate(sql);

                        if (excluir == 1) {
                            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                            con_loja_de_jogos.executaSQL("select * from jogo order by CodJogo");
                            con_loja_de_jogos.resultset.first();
                            preencherTabela();
                            posicionarRegistro();
                            consultarFaixaEtaria();
                            consultarOBS();
                        } else {
                            JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }

                } catch (SQLException excecao) {
                    JOptionPane.showMessageDialog(null, "Erro na exclusão: " + excecao, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCodJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodJogoActionPerformed

    }//GEN-LAST:event_txtCodJogoActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtDtLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtLancamentoActionPerformed

    private void txtAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvaliacaoActionPerformed

    }//GEN-LAST:event_txtAvaliacaoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtCodJogo.setText("");
        txtnome.setText("");
        txtDtLancamento.setText("");
        txtAvaliacao.setText("");
        txtCodFaixaEtaria.setText("");
        txtReqMinId.setText("");
        txtPreco.setText("");
        txtCodJogo.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
                String nome = txtnome.getText();
                String DtLancamento = txtDtLancamento.getText();
                String avaliacao = txtAvaliacao.getText();
                String CodFaixaEtaria = txtCodFaixaEtaria.getText();
                String ReqMinId = txtReqMinId.getText();
                String Preco = txtPreco.getText();

                try {
                    
             
                        String checkFaixaEtariaQuery = "SELECT 1 FROM ClassificacaoIndicativa WHERE CodFaixaEtaria = ?";
                        PreparedStatement pstmtFaixaEtaria = con_loja_de_jogos.prepareStatement(checkFaixaEtariaQuery);
                        pstmtFaixaEtaria.setString(1, CodFaixaEtaria);
                        ResultSet rsClassificacaoIndicativa = pstmtFaixaEtaria.executeQuery();

    if (!rsClassificacaoIndicativa.next()) {
        JOptionPane.showMessageDialog(null, "Classificação não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  
    }
    
                        String checkOBSQuery = "SELECT 6 FROM ReqMinimos WHERE ReqMinId = ?";
                        PreparedStatement pstmtOBS = con_loja_de_jogos.prepareStatement(checkOBSQuery);
                        pstmtOBS.setString(1, ReqMinId);
                        ResultSet rsOBS = pstmtOBS.executeQuery();

    if (!rsOBS.next()) {
        JOptionPane.showMessageDialog(null, "Observações não encontradas!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  
    }

                    String insert_sql = "insert into jogo (nome, DtLancamento, avaliacao, CodFaixaEtaria, ReqMinId, Preco) values ('" + nome + "','" + DtLancamento + "','" + avaliacao + "','" + CodFaixaEtaria + "','" + ReqMinId  +  "','" + Preco + "')";
                    con_loja_de_jogos.statement.executeUpdate(insert_sql);

                    JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

                    con_loja_de_jogos.executaSQL("select * from jogo order by CodJogo");
                    preencherTabela();
                    consultarFaixaEtaria();
                    consultarOBS();
                } catch (SQLException errosql) {
                    JOptionPane.showMessageDialog(null, "\n Erro de gravação :\n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        try {
                    con_loja_de_jogos.resultset.first();
                    mostrar_Dados();
                    consultarFaixaEtaria();
                    consultarOBS();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnLogin2ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            String pesquisa = "select * from Jogo where CodJogo like '" + txtPesquisar.getText() + "%'";
            con_loja_de_jogos.executaSQL(pesquisa);

            if (con_loja_de_jogos.resultset.first()) {
                preencherTabela();
                consultarFaixaEtaria();
                consultarOBS();
            } else {
                JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Jogo(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel rPesquisar;
    private javax.swing.JLabel rReqMinId;
    private javax.swing.JLabel rReqMinId1;
    private javax.swing.JLabel rReqMinId2;
    private javax.swing.JLabel rReqMinId3;
    private javax.swing.JTable tbljogo;
    private javax.swing.JTextField txtAvaliacao;
    private javax.swing.JTextField txtCodFaixaEtaria;
    private javax.swing.JTextField txtCodJogo;
    private javax.swing.JTextField txtDtLancamento;
    private javax.swing.JTextField txtFaixaEtaria;
    private javax.swing.JTextField txtOBS;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtReqMinId;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables

  public void preencherTabela() {

        tbljogo.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbljogo.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbljogo.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbljogo.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbljogo.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbljogo.getColumnModel().getColumn(5).setPreferredWidth(100);
        tbljogo.getColumnModel().getColumn(5).setPreferredWidth(100);

        DefaultTableModel modelo = (DefaultTableModel) tbljogo.getModel();
        modelo.setNumRows(1);

        try {
            con_loja_de_jogos.resultset.beforeFirst();
            while (con_loja_de_jogos.resultset.next()) {
                modelo.addRow(new Object[]{
                    con_loja_de_jogos.resultset.getString("CodJogo"), con_loja_de_jogos.resultset.getString("nome"), con_loja_de_jogos.resultset.getString("Dtlancamento"), con_loja_de_jogos.resultset.getString("avaliacao"), con_loja_de_jogos.resultset.getString("CodFaixaEtaria"), con_loja_de_jogos.resultset.getString("ReqMinId"), con_loja_de_jogos.resultset.getString("Preco")
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "\n Erro ao listar dados da tabela!! :\n " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void posicionarRegistro() {

        try {
            con_loja_de_jogos.resultset.first();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
   private void consultarFaixaEtaria() {
    String CodFaixaEtaria = txtCodFaixaEtaria.getText();
    String ClassificacaoIndicativa = "";

    try {
        // Certifique-se que a conexão (con_loja_de_FaixaEtarias) está inicializada e ativa
        String FaixaEtariaQuery = "SELECT ClassificacaoIndicativa FROM ClassificacaoIndicativa WHERE CodFaixaEtaria = ?";
        PreparedStatement pstmt = con_loja_de_jogos.prepareStatement(FaixaEtariaQuery);
        pstmt.setString(1, CodFaixaEtaria);
        ResultSet rsFaixaEtaria = pstmt.executeQuery();
        
        if (rsFaixaEtaria.next()) {
            ClassificacaoIndicativa = rsFaixaEtaria.getString("ClassificacaoIndicativa");
            txtFaixaEtaria.setText(ClassificacaoIndicativa);
        } else {
            txtFaixaEtaria.setText("   N/A");
        }
        
        rsFaixaEtaria.close();
        pstmt.close(); // Lembre-se de fechar os recursos
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao consultar jogo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Para ajudar no diagnóstico do erro
    }
}

private void consultarOBS() {
    String ReqMinId = txtReqMinId.getText();
    String OBS = "";

    try {
        // Certifique-se que a conexão (con_loja_de_jogos) está inicializada e ativa
        String OBSQuery = "SELECT OBS FROM ReqMinimos WHERE ReqMinId = ?";
        PreparedStatement pstmt = con_loja_de_jogos.prepareStatement(OBSQuery);
        pstmt.setString(1, ReqMinId);
        ResultSet rsOBS = pstmt.executeQuery();
        
        if (rsOBS.next()) {
            OBS = rsOBS.getString("OBS");
            txtOBS.setText(OBS);
        } else {
            txtOBS.setText("N/A");
        }
        
        rsOBS.close();
        pstmt.close(); // Lembre-se de fechar os recursos
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao consultar OBS: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Para ajudar no diagnóstico do erro
    }
}
    public void mostrar_Dados() {

        try {
            txtCodJogo.setText(con_loja_de_jogos.resultset.getString("CodJogo"));
            txtnome.setText(con_loja_de_jogos.resultset.getString("Nome"));
            txtDtLancamento.setText(con_loja_de_jogos.resultset.getString("DtLancamento"));
            txtAvaliacao.setText(con_loja_de_jogos.resultset.getString("Avaliacao"));
            txtCodFaixaEtaria.setText(con_loja_de_jogos.resultset.getString("CodFaixaEtaria"));
            txtReqMinId.setText(con_loja_de_jogos.resultset.getString("ReqMinId"));
            txtPreco.setText(con_loja_de_jogos.resultset.getString("Preco"));

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }


}

