/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package controle;
import conexao.Conexao; 
import conexao.Conexao;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author henri
 */
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
             
public class NotaFiscalJogo extends JDialog {
  Conexao con_loja_de_jogos;

    /**
     * Creates new form Jogo
     * @param owner
     * @param title
     * @param modal
     */
    public NotaFiscalJogo(Frame owner, String title, boolean modal) {
        super(owner, title, modal);
        initComponents();
        ImageIcon icone = new ImageIcon("src/img/NOVA.png");
        setIconImage(icone.getImage());
        con_loja_de_jogos = new Conexao();
        con_loja_de_jogos.conecta();
        
        
             addWindowListener(new WindowAdapter() {
            @Override
                public void windowOpened(WindowEvent e) {
                consultarCliente();
                consultarJogo();
            }
        });
        
txtCodNotaFiscal.addKeyListener(new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
        consultarCliente();
 
    }
});

txtCodJogo.addKeyListener(new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
        consultarJogo();
    }
});

        con_loja_de_jogos.executaSQL("select * from NotaFiscalJogo order by CodNotaFiscal");
        preencherTabela();
        posicionarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotaFiscalJogo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnNova = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodJogo = new javax.swing.JTextField();
        txtCodNotaFiscal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnGravar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtQtdVend = new javax.swing.JTextField();
        txtCodCliente = new javax.swing.JTextField();
        txtNomeJogo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnPrimeiro = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        rPesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(24, 26, 33));
        jPanel2.setPreferredSize(new java.awt.Dimension(851, 1107));

        tblNotaFiscalJogo.setBackground(new java.awt.Color(51, 54, 61));
        tblNotaFiscalJogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNotaFiscalJogo.setForeground(new java.awt.Color(204, 204, 204));
        tblNotaFiscalJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CodNotaFiscal", "CodJogo", "QtdVend"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNotaFiscalJogo.setName("tblNotaFiscalJogo"); // NOI18N
        tblNotaFiscalJogo.setPreferredSize(new java.awt.Dimension(525, 100));
        jScrollPane2.setViewportView(tblNotaFiscalJogo);

        jPanel3.setBackground(new java.awt.Color(75, 65, 119));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nova_resized.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(627, 398));
        jLabel9.setMinimumSize(new java.awt.Dimension(627, 398));
        jLabel9.setPreferredSize(new java.awt.Dimension(627, 398));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnNova.setBackground(new java.awt.Color(75, 65, 119));
        btnNova.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnNova.setForeground(new java.awt.Color(255, 255, 255));
        btnNova.setText("NOVA Indie");
        btnNova.setName("btnLogin"); // NOI18N
        btnNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNova)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNova)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(51, 54, 61));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código do Jogo");

        txtCodJogo.setBackground(new java.awt.Color(75, 77, 77));
        txtCodJogo.setForeground(new java.awt.Color(225, 225, 225));
        txtCodJogo.setToolTipText("");
        txtCodJogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodJogo.setInheritsPopupMenu(true);
        txtCodJogo.setName("txtCodJogo"); // NOI18N
        txtCodJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodJogoActionPerformed(evt);
            }
        });

        txtCodNotaFiscal.setBackground(new java.awt.Color(75, 77, 77));
        txtCodNotaFiscal.setForeground(new java.awt.Color(225, 225, 225));
        txtCodNotaFiscal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodNotaFiscal.setName("txtCodNotaFiscal"); // NOI18N
        txtCodNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodNotaFiscalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código da Nota Fiscal");

        jLabel7.setBackground(new java.awt.Color(75, 65, 119));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CAMPO ASSOCIATIVO DA TABELA DE NOTA FISCAL COM JOGO");

        btnExcluir.setBackground(new java.awt.Color(75, 65, 119));
        btnExcluir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(75, 65, 119));
        btnAlterar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(75, 65, 119));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setName("btnLimpar"); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(75, 65, 119));
        btnNovo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo Registro");
        btnNovo.setName("btnnovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setBackground(new java.awt.Color(75, 65, 119));
        btnGravar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(255, 255, 255));
        btnGravar.setText("Gravar");
        btnGravar.setName("btnGravar"); // NOI18N
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade de Produtos Comprados");

        txtQtdVend.setBackground(new java.awt.Color(75, 77, 77));
        txtQtdVend.setForeground(new java.awt.Color(225, 225, 225));
        txtQtdVend.setToolTipText("");
        txtQtdVend.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtQtdVend.setInheritsPopupMenu(true);
        txtQtdVend.setName("txtQtdVend"); // NOI18N
        txtQtdVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdVendActionPerformed(evt);
            }
        });

        txtCodCliente.setEditable(false);
        txtCodCliente.setBackground(new java.awt.Color(57, 57, 58));
        txtCodCliente.setForeground(new java.awt.Color(225, 225, 225));
        txtCodCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodCliente.setName("txtGenero"); // NOI18N
        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });

        txtNomeJogo.setEditable(false);
        txtNomeJogo.setBackground(new java.awt.Color(57, 57, 58));
        txtNomeJogo.setForeground(new java.awt.Color(225, 225, 225));
        txtNomeJogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNomeJogo.setName("txtGenero"); // NOI18N
        txtNomeJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeJogoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Código do Nota Fiscal");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome do Jogo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnGravar)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCodNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(txtCodJogo))
                                    .addComponent(txtQtdVend))
                                .addGap(261, 261, 261))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(143, 143, 143)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtQtdVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnNovo.getAccessibleContext().setAccessibleDescription("");

        jLabel8.setBackground(new java.awt.Color(75, 65, 119));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tabela de associação da Tabela de Notas Fiscais com a tabela Jogo");

        btnAnterior.setBackground(new java.awt.Color(75, 65, 119));
        btnAnterior.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Anterior");
        btnAnterior.setName("btnAnterior"); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setBackground(new java.awt.Color(75, 65, 119));
        btnUltimo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnUltimo.setForeground(new java.awt.Color(255, 255, 255));
        btnUltimo.setText("Último");
        btnUltimo.setActionCommand("Ùltimo");
        btnUltimo.setName("btnUltimo"); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnProximo.setBackground(new java.awt.Color(75, 65, 119));
        btnProximo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnProximo.setForeground(new java.awt.Color(255, 255, 255));
        btnProximo.setText("Próximo");
        btnProximo.setName("btnProximo"); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));

        btnPrimeiro.setBackground(new java.awt.Color(75, 65, 119));
        btnPrimeiro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnPrimeiro.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.setActionCommand("Ùltimo");
        btnPrimeiro.setName("btnUltimo"); // NOI18N
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(75, 65, 119));
        btnPesquisar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setLabel("Pesquisar");
        btnPesquisar.setName("btnPesquisar"); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.setBackground(new java.awt.Color(75, 77, 77));
        txtPesquisar.setForeground(new java.awt.Color(225, 225, 225));
        txtPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPesquisar.setName("txtEmail"); // NOI18N

        rPesquisar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        rPesquisar.setText("Pesquisar por Código:");
        rPesquisar.setName("rPesquisar"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(rPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnPesquisar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
                try {
                    con_loja_de_jogos.resultset.previous();
                    mostrar_Dados();
                    consultarCliente();
                    consultarJogo();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
                try {
                    con_loja_de_jogos.resultset.next();
                    mostrar_Dados();
                    consultarCliente();
                    consultarJogo();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }           
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
     try {
                    con_loja_de_jogos.resultset.last();
                    mostrar_Dados();
                    consultarCliente();
                    consultarJogo();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        try {
                    con_loja_de_jogos.resultset.first();
                    mostrar_Dados();
                    consultarCliente();
                    consultarJogo();
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(null, "Não foi possivel acessar o primeiro registro");
                }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnNovaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            String pesquisa = "select * from NotaFiscalJogo where CodNotaFiscal like '" + txtPesquisar.getText() + "%'";
            con_loja_de_jogos.executaSQL(pesquisa);

            if (con_loja_de_jogos.resultset.first()) {
                preencherTabela();
                consultarCliente();
                consultarJogo();
            } else {
                JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
      String CodNotaFiscal = txtCodNotaFiscal.getText();
      String CodJogo = txtCodJogo.getText();
      String QtdVend = txtQtdVend.getText();

try {

    String checkNotaFiscalQuery = "SELECT 1 FROM NotaFiscal WHERE CodNotaFiscal = ?";
    PreparedStatement pstmtNotaFiscal = con_loja_de_jogos.prepareStatement(checkNotaFiscalQuery);
    pstmtNotaFiscal.setString(1, CodNotaFiscal);
    ResultSet rsNotaFiscal = pstmtNotaFiscal.executeQuery();

    if (!rsNotaFiscal.next()) {

        JOptionPane.showMessageDialog(null, "Código de Nota Fiscal não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return; 
    }


    String checkJogoQuery = "SELECT 1 FROM jogo WHERE CodJogo = ?";
    PreparedStatement pstmtJogo = con_loja_de_jogos.prepareStatement(checkJogoQuery);
    pstmtJogo.setString(1, CodJogo);
    ResultSet rsJogo = pstmtJogo.executeQuery();

    if (!rsJogo.next()) {

        JOptionPane.showMessageDialog(null, "Código do Jogo não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return; 
    }


    String insert_sql = "INSERT INTO NotaFiscalJogo (CodNotaFiscal, CodJogo, QtdVend) VALUES (?, ?, ?)";
    PreparedStatement pstmtInsert = con_loja_de_jogos.prepareStatement(insert_sql);
    pstmtInsert.setString(1, CodNotaFiscal);
    pstmtInsert.setString(2, CodJogo);
    pstmtInsert.setString(3, QtdVend);
    pstmtInsert.executeUpdate();

    JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);


    con_loja_de_jogos.executaSQL("SELECT * FROM NotaFiscalJogo ORDER BY CodNotaFiscal");
    preencherTabela();
    consultarCliente();
    consultarJogo();

} catch (SQLException errosql) {
    JOptionPane.showMessageDialog(null, "\n Erro de gravação:\n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
}


    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        txtCodNotaFiscal.setText("");
        txtCodJogo.setText("");
        txtQtdVend.setText("");
        txtNomeJogo.setText("");
        txtCodCliente.setText("");
        txtCodNotaFiscal.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        txtCodNotaFiscal.setText("");
        txtCodJogo.setText("");
        txtQtdVend.setText("");
        txtNomeJogo.setText("");
        txtCodCliente.setText("");
        txtCodNotaFiscal.requestFocus();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
String CodJogo = txtCodJogo.getText();
String CodNotaFiscal = txtCodNotaFiscal.getText();  
String QtdVend = txtQtdVend.getText();  

String sql;
String msg = "";

try {

    String checkNotaFiscalQuery = "SELECT 1 FROM NotaFiscal WHERE CodNotaFiscal = ?";
    PreparedStatement pstmtNotaFiscal = con_loja_de_jogos.prepareStatement(checkNotaFiscalQuery);
    pstmtNotaFiscal.setString(1, CodNotaFiscal);
    ResultSet rsNotaFiscal = pstmtNotaFiscal.executeQuery();

    if (!rsNotaFiscal.next()) {
        JOptionPane.showMessageDialog(null, "Código de Nota Fiscal não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  
    }


    String checkJogoQuery = "SELECT 1 FROM jogo WHERE CodJogo = ?";
    PreparedStatement pstmtJogo = con_loja_de_jogos.prepareStatement(checkJogoQuery);
    pstmtJogo.setString(1, CodJogo);
    ResultSet rsJogo = pstmtJogo.executeQuery();

    if (!rsJogo.next()) {
        JOptionPane.showMessageDialog(null, "Código do Jogo não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  
    }


    sql = "UPDATE NotaFiscalJogo SET QtdVend = ? WHERE CodNotaFiscal = ? AND CodJogo = ?";
    PreparedStatement pstmtUpdate = con_loja_de_jogos.prepareStatement(sql);
    pstmtUpdate.setString(1, QtdVend);
    pstmtUpdate.setString(2, CodNotaFiscal);
    pstmtUpdate.setString(3, CodJogo);

    int rowsAffected = pstmtUpdate.executeUpdate();

    if (rowsAffected == 0) {
        JOptionPane.showMessageDialog(null, "Nenhum registro encontrado para alterar!", "Erro", JOptionPane.ERROR_MESSAGE);
        
    } else {
        JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

        con_loja_de_jogos.executaSQL("SELECT * FROM NotaFiscalJogo ORDER BY CodNotaFiscal");
        preencherTabela();
        consultarCliente();
        consultarJogo();
    }

} catch (SQLException errosql) {
    JOptionPane.showMessageDialog(null, "\nErro na gravação:\n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
}

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
                                        
    String sql = "";

    try {

        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
        if (resposta == JOptionPane.YES_OPTION) {

            sql = "DELETE FROM NotaFiscalJogo WHERE CodNotaFiscal = ? AND CodJogo = ? AND QtdVend = ?";
            PreparedStatement pstmtExcluir = con_loja_de_jogos.prepareStatement(sql);
            
            pstmtExcluir.setString(1, txtCodNotaFiscal.getText());  
            pstmtExcluir.setString(2, txtCodJogo.getText());      
            pstmtExcluir.setString(3, txtQtdVend.getText());     
            
            int excluir = pstmtExcluir.executeUpdate();

            if (excluir > 0) {
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

                con_loja_de_jogos.executaSQL("SELECT * FROM NotaFiscalJogo ORDER BY CodNotaFiscal");
                con_loja_de_jogos.resultset.first();
                preencherTabela();
                posicionarRegistro();
                consultarCliente();
                consultarJogo();
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum registro encontrado para exclusão!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } catch (SQLException excecao) {
        JOptionPane.showMessageDialog(null, "Erro na exclusão: " + excecao, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCodNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodNotaFiscalActionPerformed

    }//GEN-LAST:event_txtCodNotaFiscalActionPerformed

    private void txtCodJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodJogoActionPerformed

    private void txtQtdVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdVendActionPerformed

    private void txtNomeJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeJogoActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void NotaFiscalJogo(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNova;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel rPesquisar;
    private javax.swing.JTable tblNotaFiscalJogo;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodJogo;
    private javax.swing.JTextField txtCodNotaFiscal;
    private javax.swing.JTextField txtNomeJogo;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtQtdVend;
    // End of variables declaration//GEN-END:variables

  public void preencherTabela() {

        tblNotaFiscalJogo.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblNotaFiscalJogo.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblNotaFiscalJogo.getColumnModel().getColumn(2).setPreferredWidth(100);

        DefaultTableModel modelo = (DefaultTableModel) tblNotaFiscalJogo.getModel();
        modelo.setNumRows(1);

        try {
            con_loja_de_jogos.resultset.beforeFirst();
            while (con_loja_de_jogos.resultset.next()) {
                modelo.addRow(new Object[]{
                    con_loja_de_jogos.resultset.getString("CodNotaFiscal"), con_loja_de_jogos.resultset.getString("CodJogo"), con_loja_de_jogos.resultset.getString("QtdVend")
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "\n Erro ao listar dados da tabela!! :\n " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void posicionarRegistro() {

        try {
            con_loja_de_jogos.resultset.first();
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void consultarJogo() {
    String CodJogo = txtCodJogo.getText();
    String nomeJogo = "";

    try {
        
        String jogoQuery = "SELECT Nome FROM jogo WHERE CodJogo = ?";
        PreparedStatement pstmt = con_loja_de_jogos.prepareStatement(jogoQuery);
        pstmt.setString(1, CodJogo);
        ResultSet rsJogo = pstmt.executeQuery();

        if (rsJogo.next()) {
            nomeJogo = rsJogo.getString("Nome");
            txtNomeJogo.setText(nomeJogo);
        } else {
            txtNomeJogo.setText("N/A");
        }
        
        rsJogo.close();
        pstmt.close();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao consultar jogo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); 
    }
}

private void consultarCliente() {
    String CodNotaFiscal = txtCodNotaFiscal.getText();
    String codCliente = "";

    try {

        String clienteQuery = "SELECT CodCliente FROM NotaFiscal WHERE CodNotaFiscal = ?";
        PreparedStatement pstmt = con_loja_de_jogos.prepareStatement(clienteQuery);
        pstmt.setString(1, CodNotaFiscal);
        ResultSet rsCliente = pstmt.executeQuery();
        
        if (rsCliente.next()) {
            codCliente = rsCliente.getString("CodCliente");
            txtCodCliente.setText(codCliente);

        } else {
            txtCodCliente.setText("N/A");
        }
        
        rsCliente.close();
        pstmt.close(); 
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao consultar cliente: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); 
    }
}
    public void mostrar_Dados() {

        try {
            txtCodNotaFiscal.setText(con_loja_de_jogos.resultset.getString("CodNotaFiscal"));
            txtCodJogo.setText(con_loja_de_jogos.resultset.getString("CodJogo"));
            txtQtdVend.setText(con_loja_de_jogos.resultset.getString("QtdVend"));
            

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }


}

